StocksWebApp/ViewModels/OrderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StocksWebApp.ViewModels
{
    public class OrderViewModel
    {
        public int ID { get; set; }
        public int StockID { get; set; }
        public int AccountID { get; set; }
        public int Shares { get; set; }
        public double Limit { get; set; }
        public string Type { get; set; }
        public double TotalPrice { get; set; }
        public bool Completed { get; set; }
        public string StockName { get; set; }
        public string IndexSymbol { get; set; }
    }
}

StocksWebApp/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using StocksWebApp.ViewModels;
using StocksWebApp.Converters;
using DataLibrary.DALs;
using StocksBusinessLayer.Models;
using StocksBusinessLayer.Containers;
using StocksWebApp.ClassHelp;

namespace StocksWebApp.Controllers
{
    public class OrderController : Controller
    {
        public static readonly string ConnString = "Server=home.wietze.xyz;Database=RoelStam;User Id=RoelStam;Password=Test3211!";
        //public static readonly string ConnString = @"Server=localhost\SQLEXPRESS;Database=Admin;Trusted_Connection=True;";
        private readonly OrderConverter orderConverter = new OrderConverter();
        private readonly StockConverter stockConverter = new StockConverter();
        private readonly IndexConverter indexConverter = new IndexConverter();
        private readonly OrderContainer orderContainer = new OrderContainer(new DALOrder(ConnString));
        private readonly StockContainer stockContainer = new StockContainer(new DALStock(ConnString));
        private readonly IndexContainer indexContainer = new IndexContainer(new DALIndex(ConnString));
        OrderClassHelp orderClassHelp = new OrderClassHelp(new DALHolding(ConnString),
                                                           new DALAccount(ConnString),
                                                           new DALWallet(ConnString));

        public IActionResult Index()
        {
            try
            {
                var model = new OrderIndexViewModel
                {

                    OrderViewModels = orderConverter.Convert(orderContainer.GetAllOrdersByAccountID(3))
                };
                foreach (var order in model.OrderViewModels)
                {
                    order.StockName = stockContainer.GetStockByID(order.StockID).Name;
                    order.IndexSymbol = indexContainer.GetIndexByID(stockContainer.GetStockByID(order.StockID).IndexID).Symbol;
                }
                return View(model);
            }
            catch(Exception error)
            {
                return RedirectToAction("Error", "Error", new { error = error.Message });
            }
        }

        public IActionResult Detail(int id)
        {
            try
            {
                OrderViewModel order = orderConverter.Convert(orderContainer.GetOrderByID(id));
                var model = new OrderDetailViewModel
                {
                    orderViewModel = order
                };
                model.stockViewModel = stockConverter.Convert(stockContainer.GetStockByID(order.StockID));
                model.indexViewModel = indexConverter.Convert(indexContainer.GetIndexByID(model.stockViewModel.IndexID));
                return View(model);
            }
            catch (Exception error)
            {
                return RedirectToAction("Error", "Error", new { error = error.Message });
            }
        }

        [HttpGet]
        public IActionResult PlaceOrder(int stockID)
        {
            var model = new OrderAddViewModel();
            var modelStock = stockConverter.Convert(stockContainer.GetStockByID(stockID));
            var modelIndex = indexConverter.Convert(indexContainer.GetIndexByID(modelStock.IndexID));
            model.StockID = stockID;
            model.StockChange = modelStock.Change;
            model.StockPrice = modelStock.Price;
            model.StockSymbol = modelStock.Symbol;
            model.StockName = modelStock.Name;
            model.IndexName = modelIndex.Name;
            model.IndexSymbol = modelIndex.Symbol;
            model.AccountID = 3;
            return View(model);
        }

        [HttpPost]
        public IActionResult PlaceOrder(OrderAddViewModel model, int StockID)
        {
            try
            {
                var order = new Order();
                order.StockID = model.StockID;
                order.AccountID = 3;
                order.Shares = model.Shares;
                order.Limit = model.Limit;
                order.Type = model.Type;
                order.TotalPrice = model.Shares * model.Limit;
                var order1 = new Order
                {
                    Type = order.Type,
                    StockID = order.StockID,
                    AccountID = order.AccountID,
                    Limit = order.Limit,
                    TotalPrice = order.TotalPrice
                };
                if (orderClassHelp.CheckOrder(order1))
                {
                    order.AddOrder(new DALOrder(ConnString));
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("PlaceOrder", new { StockID = StockID });
                }
            }
            catch (Exception error)
            {
                return RedirectToAction("Error", "Error", new { error = error.Message });
            }
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var model = orderConverter.Convert(orderContainer.GetOrderByID(id));
            return View(model);
        }

        [HttpPost]
        public IActionResult Update(OrderViewModel model, int id)
        {
            try
            {
                var order = orderContainer.GetOrderByID(id);
                order.StockID = orderConverter.Convert(orderContainer.GetOrderByID(id)).StockID;
                order.AccountID = 3;
                order.Shares = model.Shares;
                order.Limit = model.Limit;
                order.TotalPrice = order.Shares * order.Limit;
                if (orderClassHelp.CheckOrder(order))
                {
                    order.UpdateOrder(new DALOrder(ConnString));
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Update", new { id = id });
                }
            }
            catch (Exception error)
            {
                return RedirectToAction("Error", "Error", new { error = error.Message });
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var model = orderConverter.Convert(orderContainer.GetOrderByID(id));
            model.StockName = stockConverter.Convert(stockContainer.GetStockByID(model.StockID)).Name;
            model.IndexSymbol = indexConverter.Convert(indexContainer.GetIndexByID(stockConverter.Convert(stockContainer.GetStockByID(model.StockID)).IndexID)).Symbol;
            return View(model);
        }

        [HttpPost]
        public IActionResult DeletePost(int id)
        {
            try
            {
                orderContainer.DeleteOrder(id);
                return RedirectToAction("Index");
            }
            catch (Exception error)
            {
                return RedirectToAction("Error", "Error", new { error = error.Message });
            }
        }
    }
}

StocksWebApp/Controllers/StockController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using StocksWebApp.ViewModels;
using StocksWebApp.Models;
using StocksWebApp.Converters;
using DataLibrary.DALs;
using StocksBusinessLayer.Models;
using StocksBusinessLayer.Containers;

namespace StocksWebApp.Controllers
{
    public class StockController : Controller
    {
        public static readonly string ConnString = "Server=home.wietze.xyz;Database=RoelStam;User Id=RoelStam;Password=Test3211!";
        //public static readonly string ConnString = @"Server=localhost\SQLEXPRESS;Database=Admin;Trusted_Connection=True;";
        private readonly IndexConverter indexConverter = new IndexConverter();
        private readonly StockConverter stockConverter = new StockConverter();
        readonly WatchlistConverter watchlistConverter = new WatchlistConverter();
        private readonly StockContainer stockContainer = new StockContainer(new DALStock(ConnString));
        private readonly IndexContainer indexContainer = new IndexContainer(new DALIndex(ConnString));
        readonly WatchlistContainer watchlistContainer = new WatchlistContainer(new DALWatchlist(ConnString));

        public IActionResult Index()
        {
            var model = new StockIndexViewModel
            {
                StockViewModels = stockConverter.Convert(stockContainer.GetAllStocks()),
                Indices = indexConverter.Convert(indexContainer.GetallIndices())
            };
            foreach(var stock in model.StockViewModels)
            {
                stock.IndexSymbol = indexConverter.Convert(indexContainer.GetIndexByID(stock.IndexID)).Symbol;
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Index(StockIndexViewModel SearchModel)
        {
            var model = new StockIndexViewModel
            {
                StockViewModels = stockConverter.Convert(stockContainer.SearchStocks(SearchModel.IndexFilter, SearchModel.SearchTerm)),
                Indices = indexConverter.Convert(indexContainer.GetallIndices())
            };
            foreach (var stock in model.StockViewModels)
            {
                stock.IndexSymbol = indexConverter.Convert(indexContainer.GetIndexByID(stock.IndexID)).Symbol;
            }
            return View(model);
        }

        public IActionResult Detail(int id)
        {
            var watchlistIndexViewModel = new WatchlistIndexViewModel
            {
                Watchlists = watchlistConverter.Convert(watchlistContainer.GetWatchlistsByAccountID(3))
            };
            
            StockViewModel stock = stockConverter.Convert(stockContainer.GetStockByID(id));
            var model = new StockDetailViewModel
            {
                stock = stock,
                index = indexConverter.Convert(indexContainer.GetIndexByID(stock.IndexID)),
                watchlistViewModel = watchlistConverter.Convert(watchlistContainer.GetWatchlist(3, stock.ID)),
                watchlistIndexViewModel = watchlistIndexViewModel
            };
            return View(model);
        }

        [HttpGet]
        public IActionResult Update()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Update(int stockID)
        {
            return View();
        }
    }
}

StocksWebApp/Views/Order/Delete.cshtml
@using StocksWebApp.ViewModels
@model OrderViewModel

<form asp-action="DeletePost" asp-controller="Order" asp-route-id="@Model.ID">
    <div class="form-group">
        <p><strong>Are you sure you want to delete this order?</strong></p>
        <br />
        <div class="d-flex p-2" style="width:400px">
            <div style="width:50%; display:inline-block">
                Stock <br>
                Index <br>
                OrderID <br>
                Type <br>
                Amount <br>
                Limit <br>
            </div>
            <div style="width:50%; display: inline-block">
                <strong>
                    @Model.StockName <br>
                    @Model.IndexSymbol <br>
                    @Model.ID <br>
                    @Model.Type <br>
                    @Model.Shares <br>
                    @Model.Limit <br>
                </strong>
            </div>
        </div>
    </div>
    <button class="btn btn-primary" type="submit"> Yes </button>
    <a class="btn btn-primary" asp-action="Detail" asp-controller="Order" asp-route-id="@Model.ID"> No </a>
</form>

StocksWebApp/Views/Order/Detail.cshtml
@using StocksWebApp.ViewModels;
@model OrderDetailViewModel

<br />
<p><strong>@Model.stockViewModel.Name</strong></p>
@Model.stockViewModel.Symbol || @Model.indexViewModel.Name
@if (Model.stockViewModel.Change > 0)
{
    <p style="color:limegreen"><strong>@Model.stockViewModel.Price | @Model.stockViewModel.Change</strong></p>
}
else if (Model.stockViewModel.Change < 0)
{
    <p style="color:red"><strong>@Model.stockViewModel.Price | @Model.stockViewModel.Change</strong></p>
}
else
{
    <p><strong>@Model.stockViewModel.Price | @Model.stockViewModel.Change</strong></p>
}

<div class="d-flex p-2" style="width:400px">
    <div style="width:50%; display:inline-block">
        OrderID <br>
        Type <br>
        Amount <br>
        Limit <br>
        Total
    </div>

    <div style="width:50%; display: inline-block">
        <strong>
            @Model.orderViewModel.ID <br>
            @Model.orderViewModel.Type <br>
            @Model.orderViewModel.Shares <br>
            $@Model.orderViewModel.Limit <br>
            $@Model.orderViewModel.TotalPrice
        </strong>
    </div>
</div>

@if (!Model.orderViewModel.Completed)
{
    <a class="btn btn-primary" asp-action="Update" asp-controller="Order" asp-route-id="@Model.orderViewModel.ID">Update</a>
    <a class="btn btn-danger" asp-action="Delete" asp-controller="Order" asp-route-id="@Model.orderViewModel.ID">Delete</a>
}

<a class="btn btn-primary" asp-action="Index">Back to list</a>

StocksWebApp/Views/Order/Index.cshtml
@using StocksWebApp.ViewModels;
@model OrderIndexViewModel

<br />
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Type</th>
            <th scope="col">Stock</th>
            <th scope="col">Index</th>
            <th scope="col">Shares</th>
            <th scope="col">Price/share</th>
            <th scope="col">Completed</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var order in Model.OrderViewModels)
        {
            <tr>
                @if (order.Type == "Buy")
                {
                    <th scope="row" style="color:limegreen">
                        <a asp-action="Detail" asp-controller="Order" asp-route-id="@order.ID" style="color: inherit; text-decoration: none">
                            @order.Type
                        </a>
                    </th>
                }
                else
                {
                    <th scope="row" style="color:red">
                        <a asp-action="Detail" asp-controller="Order" asp-route-id="@order.ID" style="color: inherit; text-decoration: none">
                            @order.Type
                        </a>
                    </th>
                }
                <td>@order.StockName</td>
                <td>@order.IndexSymbol</td>
                <td>@order.Shares</td>
                <td>$@order.Limit</td>
                @if(order.Completed)
                {
                    <td>Completed</td>
                }
                else
                {
                    <td>Pending</td>
                }
            </tr>
        }
    </tbody>
</table>

StocksWebApp/Views/Order/PlaceOrder.cshtml
@using StocksWebApp.ViewModels;
@model OrderAddViewModel

<p><strong>@Model.StockName || @Model.StockSymbol</strong></p>
@Model.IndexName || @Model.IndexSymbol
@if(@Model.StockChange > 0)
{
    <p style="color:limegreen"><strong>@Model.StockPrice | @Model.StockChange</strong></p>
}
else if(@Model.StockChange < 0)
{
    <p style="color:red"><strong>@Model.StockPrice | @Model.StockChange</strong></p>
}
else
{
    <p><strong>@Model.StockPrice | @Model.StockChange</strong></p>
}

<form asp-route-stockID="@Model.StockID">

    <div class="form-group">
        <strong><label asp-for="Shares"></label></strong>
        <input class="form-control" asp-for="Shares">
    </div>
    <div class="form-group">
        <strong><label asp-for="Limit"></label></strong>
        <input class="form-control" asp-for="Limit">
    </div>
    <div class="form-group">
        <strong><label asp-for="Type"></label></strong>
        <select class="form-control" aria-label="Default select example" asp-for="Type">
            <option value="Buy">Buy</option>
            <option value="Sell">Sell</option>
        </select>
    </div>
    <a class="btn btn-danger" asp-action="Detail" asp-controller="Stock" asp-route-id="@Model.StockID">Cancel</a>
    <button class="btn btn-primary" type="submit">Submit</button>
</form>

StocksWebApp/Views/Order/Update.cshtml
@using StocksWebApp.ViewModels;
@model OrderViewModel

<br />
<form asp-action="Update" asp-controller="Order" asp-route-id="@Model.ID">
    <div class="form-group">
        <label asp-for="Shares"></label>
        <input class="form-group" asp-for="Shares">
    </div>
    <div class="form-group">
        <label asp-for="Limit"></label>
        <input class="form-group" asp-for="Limit">
    </div>

    <button class="btn btn-primary" type="submit">Update Order</button>
</form>